apiVersion: apps/v1
kind: Deployment
metadata:
  name: resize
  labels:
    app: resize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resize
  template:
    metadata:
      labels:
        app: resize
    spec:
      containers:
        - name: resize
          image: localhost/resize:v7
          env:
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
