apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag
  labels:
    app: tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag
  template:
    metadata:
      labels:
        app: tag
    spec:
      containers:
      - name: tag
        image: localhost/tag:v8
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
