apiVersion: apps/v1
kind: Deployment
metadata:
  name: grayscale
  labels:
    app: grayscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grayscale
  template:
    metadata:
      labels:
        app: grayscale
    spec:
      containers:
      - name: grayscale
        image: localhost/grayscale:v4
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
