apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detect
  labels:
    app: object-detect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detect
  template:
    metadata:
      labels:
        app: object-detect
    spec:
      containers:
      - name: object-detect
        image: localhost/object-detect:v6
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
