apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegrab
  labels:
    app: imagegrab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagegrab
  template:
    metadata:
      labels:
        app: imagegrab
    spec:
      containers:
      - name: imagegrab
        image: localhost/imagegrab:v4
        ports:
        - containerPort: 8000
        env:
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: BUCKET_NAME
          value: "images"
        - name: QUEUE_NAME
          value: "resize-queue"

apiVersion: v1
kind: Service
metadata:
  name: imagegrab
spec:
  selector:
    app: imagegrab
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30004
  type: NodePort
